credentials:
  usernames:
    josezaballa:
      email: joseluis.zaballa@student.ie.edu
      name: Jose Luis
      password: $2b$12$yaSP2a3bVEzfgdeoHR1dFe/x5y45p0aXBpr3ykgUp0KVU0a3254c6 # Capstone2023!
    gustavom:
      email: gustavom@faculty.ie.edu
      name: Gustavo
      password: $2b$12$yaSP2a3bVEzfgdeoHR1dFe/x5y45p0aXBpr3ykgUp0KVU0a3254c6 # Capstone2023!
    pepe:
      email: gustavom@faculty.ie.edu
      name: Pepe
      password: $2b$12$yaSP2a3bVEzfgdeoHR1dFe/x5y45p0aXBpr3ykgUp0KVU0a3254c6 # Capstone2023!

cookie:
  expiry_days: 30
  key: JHSF&%/&S$& 
  name: token
preauthorized:
  emails:
  - joseluis.zaballa@student.ie.edu